### ISSUE TITLE
쇼트코드만 사용 시 소셜 공유 불가

### ISSUE THREAD

**Issue by wolfkang** [chwnam/naran-social-share#15]
안녕하세요?

0.4.0 설정에서 

1. 소셜공유 사용을 비활성하거나
2. 소셜공유 사용 활성화 & 포스트 타입 선택하지 않고,

쇼트코드만 삽입했을 때, 소셜 공유가 작동하지 않습니다.
이 경우에 front.js 가 enqueue 되지 않는 것으로 보입니다.

확인 부탁드립니다.

**Comment by chwnam** [comment]
제 환경에서는 숏코드가 발견되면 올바르게 스크립트가 삽입되는 것으로 보입니다.
혹시 다른 커스터마이즈를 사용하였나요?

**Comment by chwnam** [comment]
### 상세
1. 빌더를 사용하는 경우에 해당. 빌더의 템플릿에서 숏코드로 사용하는 경우, 템플릿은 본문이 아니라서 스타일, 스크립트 삽입이 생략되어버림.
2. 그렇다고 sharable 필터를 사용해 강제로 결과를 바꿔 바리면, 두 번의 공유 버튼 출력이 일어남. 다시 말해, sharable 필터 결과를 강제로 true 로 바꾸고, 숏코드 사용한 포스트로 들어가면, 숏코드에 의한 공유 버튼과 the_content 필터에 의한 공유 버튼 둘 다 생성된다.

### 분석
- is_sharable 처리 과정에서 singular이냐, 숏코드 사용이냐, 제외된 포스트이냐에 대한 세세한 필터링이 없음.
- 빌더 같은 외부 요소에서 삽입된 숏코드의 삽입 여부를 판단하기가 매우 어려움.

### 해결 방안
- [x] 항상 헤더에 스타일 삽입 옵션 적용.
- [x] is_sharable에 singular, shortcode, exclude 에 대한 필터 적용.
